#ifndef IMAGESCALER_GLOBAL_H
#define IMAGESCALER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGESCALER_LIBRARY)
#  define IMAGESCALERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGESCALERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGESCALER_GLOBAL_H
